'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RegisterExternalLogin

    $if$ ($targetframeworkversion$ == 4.0)
    '''<summary>
    '''providerMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents providerMessage As Global.System.Web.UI.WebControls.Label
    $endif$

    '''<summary>
    '''userNameForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userNameForm As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''userName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userName As Global.System.Web.UI.WebControls.TextBox

    $if$ ($targetframeworkversion$ == 4.0)
    '''<summary>
    '''userNameMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userNameMessage As Global.System.Web.UI.WebControls.Label
    $endif$
End Class
