'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.10716.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



Partial Public Class Site
    
    Protected form1 As System.Web.UI.HtmlControls.HtmlForm
    
    Protected ScriptManager1 As System.Web.UI.ScriptManager
    
    Protected ContentPlaceHolder1 As System.Web.UI.WebControls.ContentPlaceHolder
End Class
